// Class ChromaSDKPlugin.*d4d7e654ba
// Size: 0x30 (Inherited: 0x30)
struct U*d4d7e654ba : UBlueprintFunctionLibrary {

	void PlayAnimationComposite(); // Function ChromaSDKPlugin.*d4d7e654ba.PlayAnimationComposite // Final|Native|Static|Public|BlueprintCallable // @ game+0x698536c
	void FillRandomColorsAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.FillRandomColorsAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x697d828
	void FillThresholdRGBColorsAllFramesRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillThresholdRGBColorsAllFramesRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697f0e0
	void *7191f1c462(); // Function ChromaSDKPlugin.*d4d7e654ba.*7191f1c462 // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6977f98
	void GetAnimationPlaytime(); // Function ChromaSDKPlugin.*d4d7e654ba.GetAnimationPlaytime // Final|Native|Static|Public|BlueprintCallable // @ game+0x6980240
	void MultiplyTargetColorLerpAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyTargetColorLerpAllFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x69840e8
	void CopyNonZeroTargetAllKeysAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroTargetAllKeysAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x697aaf0
	void FillRandomColorsBlackAndWhiteAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillRandomColorsBlackAndWhiteAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697dac8
	void CopyNonZeroAllKeysAllFramesOffset(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroAllKeysAllFramesOffset // Final|Native|Static|Public|BlueprintCallable // @ game+0x6979848
	void ReduceFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.ReduceFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x69858a0
	void SubtractNonZeroAllKeys(); // Function ChromaSDKPlugin.*d4d7e654ba.SubtractNonZeroAllKeys // Final|Native|Static|Public|BlueprintCallable // @ game+0x69895b0
	void DuplicateFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.DuplicateFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697ba98
	void LerpColorBGR(); // Function ChromaSDKPlugin.*d4d7e654ba.LerpColorBGR // Final|Native|Static|Public|BlueprintCallable // @ game+0x6981b44
	void FadeEndFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.FadeEndFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x697bc80
	void StopAnimationComposite(); // Function ChromaSDKPlugin.*d4d7e654ba.StopAnimationComposite // Final|Native|Static|Public|BlueprintCallable // @ game+0x6988a2c
	void CopyNonZeroKeysColorAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroKeysColorAllFramesName // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x697a640
	void CopyNonZeroKeysColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroKeysColorName // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x697a7e0
	void StreamBroadcastEnd(); // Function ChromaSDKPlugin.*d4d7e654ba.StreamBroadcastEnd // Final|Native|Static|Public|BlueprintCallable // @ game+0x6988d64
	void CopyKeysColor(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyKeysColor // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6978e10
	void GetPlayingAnimationCount(); // Function ChromaSDKPlugin.*d4d7e654ba.GetPlayingAnimationCount // Final|Native|Static|Public|BlueprintCallable // @ game+0x6980f04
	void GetAnimationName(); // Function ChromaSDKPlugin.*d4d7e654ba.GetAnimationName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6980160
	void MakeBlankFramesRandomBlackAndWhite(); // Function ChromaSDKPlugin.*d4d7e654ba.MakeBlankFramesRandomBlackAndWhite // Final|Native|Static|Public|BlueprintCallable // @ game+0x6982610
	void MultiplyColorLerpAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyColorLerpAllFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x69829d8
	void CopyNonZeroKeyColor(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroKeyColor // Final|Native|Static|Public|BlueprintCallable // @ game+0x6979fe0
	void GetCurrentFrameName(); // Function ChromaSDKPlugin.*d4d7e654ba.GetCurrentFrameName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6980490
	void InsertFrameName(); // Function ChromaSDKPlugin.*d4d7e654ba.InsertFrameName // Final|Native|Static|Public|BlueprintCallable // @ game+0x69814d0
	void GetKeyboardRzKey(); // Function ChromaSDKPlugin.*d4d7e654ba.GetKeyboardRzKey // Final|Native|Static|Public|BlueprintCallable // @ game+0x6980b60
	void AddNonZeroTargetAllKeysAllFramesOffset(); // Function ChromaSDKPlugin.*d4d7e654ba.AddNonZeroTargetAllKeysAllFramesOffset // Final|Native|Static|Public|BlueprintCallable // @ game+0x69774a0
	void FillColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillColorName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697c6b8
	void UnloadAnimation(); // Function ChromaSDKPlugin.*d4d7e654ba.UnloadAnimation // Final|Native|Static|Public|BlueprintCallable // @ game+0x698a920
	void CopyNonZeroAllKeysAllFramesOffsetName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroAllKeysAllFramesOffsetName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6979998
	void FillThresholdColorsAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillThresholdColorsAllFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697decc
	void InsertFrame(); // Function ChromaSDKPlugin.*d4d7e654ba.InsertFrame // Final|Native|Static|Public|BlueprintCallable // @ game+0x69813ac
	void TrimEndFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.TrimEndFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x698a448
	void CopyAnimation(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyAnimation // Final|Native|Static|Public|BlueprintCallable // @ game+0x6978874
	void FillNonZeroColor(); // Function ChromaSDKPlugin.*d4d7e654ba.FillNonZeroColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697cbcc
	void SetKeyboardKeyColor(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeyboardKeyColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6986e84
	void FillNonZeroColorRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillNonZeroColorRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697d55c
	void GetKeyColor(); // Function ChromaSDKPlugin.*d4d7e654ba.GetKeyColor // Final|Native|Static|Public|HasDefaults|BlueprintCallable // @ game+0x69806a0
	void GetMaxColumn(); // Function ChromaSDKPlugin.*d4d7e654ba.GetMaxColumn // Final|Native|Static|Public|BlueprintCallable // @ game+0x6980c3c
	void SetKeysColor(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeysColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6986fec
	void FillThresholdColorsAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.FillThresholdColorsAllFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697dd88
	void CopyNonZeroAllKeysAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroAllKeysAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6979714
	void SetKeyColor(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeyColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6986018
	void StreamGetStatus(); // Function ChromaSDKPlugin.*d4d7e654ba.StreamGetStatus // Final|Native|Static|Public|BlueprintCallable // @ game+0x69891d4
	void GetFrameCountName(); // Function ChromaSDKPlugin.*d4d7e654ba.GetFrameCountName // Final|Native|Static|Public|BlueprintCallable // @ game+0x69805e4
	void OffsetColorsAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.OffsetColorsAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x69845a8
	void SetKeysColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeysColorName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x69878d4
	void UseIdleAnimation(); // Function ChromaSDKPlugin.*d4d7e654ba.UseIdleAnimation // Final|Native|Static|Public|BlueprintCallable // @ game+0x698aa58
	void GetAnimationIdByIndex(); // Function ChromaSDKPlugin.*d4d7e654ba.GetAnimationIdByIndex // Final|Native|Static|Public|BlueprintCallable // @ game+0x698008c
	void CopyNonZeroAllKeysOffsetName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroAllKeysOffsetName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6979e14
	void IsAnimationTypePlaying(); // Function ChromaSDKPlugin.*d4d7e654ba.IsAnimationTypePlaying // Final|Native|Static|Public|BlueprintCallable // @ game+0x6981818
	void CopyZeroTargetAllKeysAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyZeroTargetAllKeysAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697b208
	void SetStaticColorAll(); // Function ChromaSDKPlugin.*d4d7e654ba.SetStaticColorAll // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6988854
	void CopyAllKeysName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyAllKeysName // Final|Native|Static|Public|BlueprintCallable // @ game+0x69786f4
	void OffsetNonZeroColors(); // Function ChromaSDKPlugin.*d4d7e654ba.OffsetNonZeroColors // Final|Native|Static|Public|BlueprintCallable // @ game+0x6984934
	void OverrideFrameDurationName(); // Function ChromaSDKPlugin.*d4d7e654ba.OverrideFrameDurationName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6985150
	void StopAnimation(); // Function ChromaSDKPlugin.*d4d7e654ba.StopAnimation // Final|Native|Static|Public|BlueprintCallable // @ game+0x698897c
	void SetCurrentFrame(); // Function ChromaSDKPlugin.*d4d7e654ba.SetCurrentFrame // Final|Native|Static|Public|BlueprintCallable // @ game+0x6985d7c
	void FillThresholdColorsAllFramesRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillThresholdColorsAllFramesRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697e1f4
	void *d9c9ec8b65(); // Function ChromaSDKPlugin.*d4d7e654ba.*d9c9ec8b65 // Final|Native|Static|Public|BlueprintCallable // @ game+0x6977f5c
	void FillColorRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.FillColorRGB // Final|Native|Static|Public|BlueprintCallable // @ game+0x697c818
	void ToBGR(); // Function ChromaSDKPlugin.*d4d7e654ba.ToBGR // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x698a238
	void StreamGetStatusString(); // Function ChromaSDKPlugin.*d4d7e654ba.StreamGetStatusString // Final|Native|Static|Public|BlueprintCallable // @ game+0x6989218
	void *a8e0445aed(); // Function ChromaSDKPlugin.*d4d7e654ba.*a8e0445aed // Final|Native|Static|Public|BlueprintCallable // @ game+0x6978150
	void GetPlayingAnimationId(); // Function ChromaSDKPlugin.*d4d7e654ba.GetPlayingAnimationId // Final|Native|Static|Public|BlueprintCallable // @ game+0x6980f44
	void CreateRandomColorsBlackAndWhite1D(); // Function ChromaSDKPlugin.*d4d7e654ba.CreateRandomColorsBlackAndWhite1D // Final|Native|Static|Public|BlueprintCallable // @ game+0x697b684
	void CopyAllKeysAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyAllKeysAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x69784c4
	void GetBGRInt(); // Function ChromaSDKPlugin.*d4d7e654ba.GetBGRInt // Final|Native|Static|Public|BlueprintCallable // @ game+0x69802d0
	void CreateColors2D(); // Function ChromaSDKPlugin.*d4d7e654ba.CreateColors2D // Final|Native|Static|Public|BlueprintCallable // @ game+0x697b420
	void Lerp(); // Function ChromaSDKPlugin.*d4d7e654ba.Lerp // Final|Native|Static|Public|BlueprintCallable // @ game+0x69818d0
	void LerpColor(); // Function ChromaSDKPlugin.*d4d7e654ba.LerpColor // Final|Native|Static|Public|HasDefaults|BlueprintCallable // @ game+0x69819fc
	void CopyNonZeroKeysColorAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroKeysColorAllFrames // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x697a4e4
	void SetKeysColorRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeysColorRGB // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6987aac
	void GetKeyboardKeyColor(); // Function ChromaSDKPlugin.*d4d7e654ba.GetKeyboardKeyColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6980964
	void OffsetColorsName(); // Function ChromaSDKPlugin.*d4d7e654ba.OffsetColorsName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6984748
	void GetRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.GetRGB // Final|Native|Static|Public|HasDefaults|BlueprintCallable // @ game+0x6980fdc
	void PlayAnimations(); // Function ChromaSDKPlugin.*d4d7e654ba.PlayAnimations // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6985584
	void AddNonZeroAllKeysAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.AddNonZeroAllKeysAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6976d08
	void FillNonZeroColorAllFramesRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.FillNonZeroColorAllFramesRGB // Final|Native|Static|Public|BlueprintCallable // @ game+0x697cf18
	void CopyNonZeroTargetAllKeysName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroTargetAllKeysName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697afa8
	void *cee6440908(); // Function ChromaSDKPlugin.*d4d7e654ba.*cee6440908 // Final|Native|Static|Public|BlueprintCallable // @ game+0x697d394
	void FillColorAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillColorAllFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697c288
	void GetAnimationCount(); // Function ChromaSDKPlugin.*d4d7e654ba.GetAnimationCount // Final|Native|Static|Public|BlueprintCallable // @ game+0x697ffa4
	void AppendAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.AppendAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x6977744
	void AddNonZeroAllKeysAllFramesOffset(); // Function ChromaSDKPlugin.*d4d7e654ba.AddNonZeroAllKeysAllFramesOffset // Final|Native|Static|Public|BlueprintCallable // @ game+0x6976e3c
	void ReverseAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.ReverseAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6985b10
	void FadeStartFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.FadeStartFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697bf48
	void StreamGetFocus(); // Function ChromaSDKPlugin.*d4d7e654ba.StreamGetFocus // Final|Native|Static|Public|BlueprintCallable // @ game+0x6988f2c
	void StreamSetFocus(); // Function ChromaSDKPlugin.*d4d7e654ba.StreamSetFocus // Final|Native|Static|Public|BlueprintCallable // @ game+0x69893b8
	void MultiplyIntensityAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyIntensityAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6982ec0
	void StreamBroadcast(); // Function ChromaSDKPlugin.*d4d7e654ba.StreamBroadcast // Final|Native|Static|Public|BlueprintCallable // @ game+0x6988c30
	void *e5c71a7711(); // Function ChromaSDKPlugin.*d4d7e654ba.*e5c71a7711 // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6977958
	void MakeBlankFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.MakeBlankFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6981d9c
	void *13b3600a71(); // Function ChromaSDKPlugin.*d4d7e654ba.*13b3600a71 // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6978080
	void FillNonZeroColorAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillNonZeroColorAllFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697ce04
	void *498443d49c(); // Function ChromaSDKPlugin.*d4d7e654ba.*498443d49c // Final|Native|Static|Public|BlueprintCallable // @ game+0x69838f0
	void PreviewFrameName(); // Function ChromaSDKPlugin.*d4d7e654ba.PreviewFrameName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6985798
	void SetStaticColor(); // Function ChromaSDKPlugin.*d4d7e654ba.SetStaticColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6988774
	void CopyNonZeroAllKeysAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroAllKeysAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x6979618
	void FillThresholdRGBColorsAllFramesRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.FillThresholdRGBColorsAllFramesRGB // Final|Native|Static|Public|BlueprintCallable // @ game+0x697ee70
	void FillColorRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillColorRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697c9e0
	void *6d1d8f534c(); // Function ChromaSDKPlugin.*d4d7e654ba.*6d1d8f534c // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6977e8c
	void FillRandomColorsBlackAndWhiteAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.FillRandomColorsBlackAndWhiteAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x697da40
	void FillZeroColorAllFramesRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillZeroColorAllFramesRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697f834
	void CloseAnimationName(); // Function ChromaSDKPlugin.*d4d7e654ba.CloseAnimationName // Final|Native|Static|Public|BlueprintCallable // @ game+0x69782f0
	void SetKeysNonZeroColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeysNonZeroColorName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6988434
	void DuplicateFirstFrameName(); // Function ChromaSDKPlugin.*d4d7e654ba.DuplicateFirstFrameName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697b908
	void IsInitialized(); // Function ChromaSDKPlugin.*d4d7e654ba.IsInitialized // Final|Native|Static|Public|BlueprintCallable // @ game+0x69818a8
	void MultiplyIntensityColorAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyIntensityColorAllFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6983524
	void OffsetColorsAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.OffsetColorsAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x698442c
	void FillColorAllFramesRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillColorAllFramesRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697c518
	void CopyKeysColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyKeysColorName // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6979308
	void OpenAnimationFromMemory(); // Function ChromaSDKPlugin.*d4d7e654ba.OpenAnimationFromMemory // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6985004
	void PlayAnimation(); // Function ChromaSDKPlugin.*d4d7e654ba.PlayAnimation // Final|Native|Static|Public|BlueprintCallable // @ game+0x6985260
	void GetAnimationId(); // Function ChromaSDKPlugin.*d4d7e654ba.GetAnimationId // Final|Native|Static|Public|BlueprintCallable // @ game+0x697ffd0
	void UnloadAnimationName(); // Function ChromaSDKPlugin.*d4d7e654ba.UnloadAnimationName // Final|Native|Static|Public|BlueprintCallable // @ game+0x698a9a8
	void CopyKeysColorAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyKeysColorAllFramesName // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6979168
	void FillRandomColorsBlackAndWhite(); // Function ChromaSDKPlugin.*d4d7e654ba.FillRandomColorsBlackAndWhite // Final|Native|Static|Public|BlueprintCallable // @ game+0x697d960
	void FillZeroColorRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillZeroColorRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697fcfc
	void SetKeyNonZeroColorAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeyNonZeroColorAllFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x698697c
	void CopyKeyColor(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyKeyColor // Final|Native|Static|Public|BlueprintCallable // @ game+0x6978ab0
	void GetMaxLeds(); // Function ChromaSDKPlugin.*d4d7e654ba.GetMaxLeds // Final|Native|Static|Public|BlueprintCallable // @ game+0x6980ccc
	void MultiplyIntensityAllFramesRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyIntensityAllFramesRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x698314c
	void CopyZeroTargetAllKeysAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyZeroTargetAllKeysAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x697b128
	void MultiplyNonZeroTargetColorLerpAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyNonZeroTargetColorLerpAllFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6983ca4
	void SetKeysColorRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeysColorRGBName // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6987cf8
	void MakeBlankFramesRandomBlackAndWhiteName(); // Function ChromaSDKPlugin.*d4d7e654ba.MakeBlankFramesRandomBlackAndWhiteName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6982728
	void CopyNonZeroAllKeys(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroAllKeys // Final|Native|Static|Public|BlueprintCallable // @ game+0x69794f4
	void FillColorAllFramesRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.FillColorAllFramesRGB // Final|Native|Static|Public|BlueprintCallable // @ game+0x697c39c
	void SubtractNonZeroAllKeysAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.SubtractNonZeroAllKeysAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x69896d4
	void MultiplyIntensityColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyIntensityColorName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6983638
	void MultiplyIntensityColorAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyIntensityColorAllFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6983430
	void TrimFrame(); // Function ChromaSDKPlugin.*d4d7e654ba.TrimFrame // Final|Native|Static|Public|BlueprintCallable // @ game+0x698a550
	void StreamGetAuthShortcode(); // Function ChromaSDKPlugin.*d4d7e654ba.StreamGetAuthShortcode // Final|Native|Static|Public|BlueprintCallable // @ game+0x6988d98
	void IsPlatformWindows(); // Function ChromaSDKPlugin.*d4d7e654ba.IsPlatformWindows // Final|Native|Static|Public|BlueprintCallable // @ game+0x59ee978
	void SetKeyNonZeroColor(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeyNonZeroColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6986650
	void CreateRandomColors1D(); // Function ChromaSDKPlugin.*d4d7e654ba.CreateRandomColors1D // Final|Native|Static|Public|BlueprintCallable // @ game+0x697b4e0
	void TrimStartFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.TrimStartFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x698a738
	void MultiplyIntensityName(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyIntensityName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6983798
	void FillZeroColorAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.FillZeroColorAllFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697f4b0
	void PreviewFrame(); // Function ChromaSDKPlugin.*d4d7e654ba.PreviewFrame // Final|Native|Static|Public|BlueprintCallable // @ game+0x69856b4
	void FillZeroColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillZeroColorName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697f9d4
	void SetKeysNonZeroColor(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeysNonZeroColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6987f64
	void StopAll(); // Function ChromaSDKPlugin.*d4d7e654ba.StopAll // Final|Native|Static|Public|BlueprintCallable // @ game+0x698892c
	void StreamWatch(); // Function ChromaSDKPlugin.*d4d7e654ba.StreamWatch // Final|Native|Static|Public|BlueprintCallable // @ game+0x6989474
	void CopyNonZeroTargetAllKeysAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroTargetAllKeysAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697abd0
	void CopyKeyColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyKeyColorName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6978c44
	void CopyNonZeroTargetAllKeysAllFramesOffsetName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroTargetAllKeysAllFramesOffsetName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697ae28
	void CopyAllKeysAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyAllKeysAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x69785c0
	void *b3ccc08cb1(); // Function ChromaSDKPlugin.*d4d7e654ba.*b3ccc08cb1 // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6977bd4
	void ReduceFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.ReduceFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6985980
	void StreamReleaseShortcode(); // Function ChromaSDKPlugin.*d4d7e654ba.StreamReleaseShortcode // Final|Native|Static|Public|BlueprintCallable // @ game+0x69892fc
	void FillThresholdColorsMinMaxAllFramesRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillThresholdColorsMinMaxAllFramesRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697e6f8
	void MultiplyIntensityAllFramesRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyIntensityAllFramesRGB // Final|Native|Static|Public|BlueprintCallable // @ game+0x6982fd0
	void ReverseAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.ReverseAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x6985a88
	void GetMaxRow(); // Function ChromaSDKPlugin.*d4d7e654ba.GetMaxRow // Final|Native|Static|Public|BlueprintCallable // @ game+0x6980d5c
	void SetKeysNonZeroColorAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeysNonZeroColorAllFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6988290
	void *4fb864378e(); // Function ChromaSDKPlugin.*d4d7e654ba.*4fb864378e // Final|Native|Static|Public|BlueprintCallable // @ game+0x6977cc0
	void SetKeysColorAllFramesRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeysColorAllFramesRGBName // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x69876b4
	void InvertColorsAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.InvertColorsAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x6981624
	void SetKeyRowColumnColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeyRowColumnColorName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6986c88
	void FillThresholdColorsRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillThresholdColorsRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697ec34
	void FillZeroColorAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillZeroColorAllFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697f5a4
	void SetKeyNonZeroColorAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeyNonZeroColorAllFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x69867fc
	void MultiplyIntensityColor(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyIntensityColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x69832ec
	void SupportsStreaming(); // Function ChromaSDKPlugin.*d4d7e654ba.SupportsStreaming // Final|Native|Static|Public|BlueprintCallable // @ game+0x698a20c
	void SetCurrentFrameName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetCurrentFrameName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6985e60
	void FillRandomColorsAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillRandomColorsAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697d8b0
	void LoadAnimationName(); // Function ChromaSDKPlugin.*d4d7e654ba.LoadAnimationName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6981cec
	void InvertColorsAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.InvertColorsAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x69816ac
	void TrimStartFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.TrimStartFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x698a818
	void SetKeysColorAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeysColorAllFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6987318
	void IsAnimationPlaying(); // Function ChromaSDKPlugin.*d4d7e654ba.IsAnimationPlaying // Final|Native|Static|Public|BlueprintCallable // @ game+0x698175c
	void CopyKeysColorAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyKeysColorAllFrames // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x697900c
	void OffsetColors(); // Function ChromaSDKPlugin.*d4d7e654ba.OffsetColors // Final|Native|Static|Public|BlueprintCallable // @ game+0x6984264
	void CopyAnimationName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyAnimationName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697897c
	void OffsetNonZeroColorsAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.OffsetNonZeroColorsAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6984c78
	void StopAnimationType(); // Function ChromaSDKPlugin.*d4d7e654ba.StopAnimationType // Final|Native|Static|Public|BlueprintCallable // @ game+0x6988adc
	void GetAnimation(); // Function ChromaSDKPlugin.*d4d7e654ba.GetAnimation // Final|Native|Static|Public|BlueprintCallable // @ game+0x697fee8
	void *84d3f11270(); // Function ChromaSDKPlugin.*d4d7e654ba.*84d3f11270 // Final|Native|Static|Public|BlueprintCallable // @ game+0x697a9cc
	void ToLinearColor(); // Function ChromaSDKPlugin.*d4d7e654ba.ToLinearColor // Final|Native|Static|Public|HasDefaults|BlueprintCallable // @ game+0x698a2d0
	void AppendAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.AppendAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6977824
	void OffsetNonZeroColorsName(); // Function ChromaSDKPlugin.*d4d7e654ba.OffsetNonZeroColorsName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6984e18
	void InsertDelay(); // Function ChromaSDKPlugin.*d4d7e654ba.InsertDelay // Final|Native|Static|Public|BlueprintCallable // @ game+0x6981134
	void SubtractNonZeroAllKeysAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.SubtractNonZeroAllKeysAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x69897d0
	void FadeEndFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.FadeEndFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697bd60
	void FillRandomColorsName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillRandomColorsName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697dc80
	void MakeBlankFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.MakeBlankFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6981f08
	void TrimEndFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.TrimEndFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x698a368
	void SubtractNonZeroTargetAllKeysAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.SubtractNonZeroTargetAllKeysAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6989e34
	void SetChromaCustomFlagName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetChromaCustomFlagName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6985c70
	void CreateRandomColorsBlackAndWhite2D(); // Function ChromaSDKPlugin.*d4d7e654ba.CreateRandomColorsBlackAndWhite2D // Final|Native|Static|Public|BlueprintCallable // @ game+0x697b768
	void SubtractNonZeroTargetAllKeysAllFramesOffset(); // Function ChromaSDKPlugin.*d4d7e654ba.SubtractNonZeroTargetAllKeysAllFramesOffset // Final|Native|Static|Public|BlueprintCallable // @ game+0x6989f68
	void AddNonZeroTargetAllKeysAllFramesOffsetName(); // Function ChromaSDKPlugin.*d4d7e654ba.AddNonZeroTargetAllKeysAllFramesOffsetName // Final|Native|Static|Public|BlueprintCallable // @ game+0x69775c4
	void FillThresholdColorsAllFramesRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.FillThresholdColorsAllFramesRGB // Final|Native|Static|Public|BlueprintCallable // @ game+0x697e02c
	void FillNonZeroColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillNonZeroColorName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697d234
	void MakeBlankFramesRandomName(); // Function ChromaSDKPlugin.*d4d7e654ba.MakeBlankFramesRandomName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6982880
	void SetKeysColorAllFramesRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeysColorAllFramesRGB // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x69874bc
	void FadeStartFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.FadeStartFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x697be68
	void *ed8dde6d01(); // Function ChromaSDKPlugin.*d4d7e654ba.*ed8dde6d01 // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6977a98
	void MakeBlankFramesRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.MakeBlankFramesRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x69822b4
	void SetKeysColorAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeysColorAllFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x69871a0
	void SubtractNonZeroTargetAllKeysAllFramesOffsetName(); // Function ChromaSDKPlugin.*d4d7e654ba.SubtractNonZeroTargetAllKeysAllFramesOffsetName // Final|Native|Static|Public|BlueprintCallable // @ game+0x698a08c
	void AddNonZeroAllKeysAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.AddNonZeroAllKeysAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x6976c0c
	void StreamWatchEnd(); // Function ChromaSDKPlugin.*d4d7e654ba.StreamWatchEnd // Final|Native|Static|Public|BlueprintCallable // @ game+0x698957c
	void CopyNonZeroKeysColor(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroKeysColor // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x697a340
	void AddNonZeroAllKeysAllFramesOffsetName(); // Function ChromaSDKPlugin.*d4d7e654ba.AddNonZeroAllKeysAllFramesOffsetName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6976f8c
	void DuplicateMirrorFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.DuplicateMirrorFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x697bb48
	void AddNonZeroTargetAllKeysAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.AddNonZeroTargetAllKeysAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x697728c
	void FillZeroColor(); // Function ChromaSDKPlugin.*d4d7e654ba.FillZeroColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697f36c
	void MultiplyNonZeroTargetColorLerpAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyNonZeroTargetColorLerpAllFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6983e08
	void CopyNonZeroTargetAllKeysAllFramesOffset(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroTargetAllKeysAllFramesOffset // Final|Native|Static|Public|BlueprintCallable // @ game+0x697ad04
	void MultiplyTargetColorLerpAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyTargetColorLerpAllFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6983f84
	void CloseAll(); // Function ChromaSDKPlugin.*d4d7e654ba.CloseAll // Final|Native|Static|Public|BlueprintCallable // @ game+0x6978244
	void GetMouseLedColor(); // Function ChromaSDKPlugin.*d4d7e654ba.GetMouseLedColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6980dec
	void UsePreloading(); // Function ChromaSDKPlugin.*d4d7e654ba.UsePreloading // Final|Native|Static|Public|BlueprintCallable // @ game+0x698abfc
	void SubtractNonZeroAllKeysName(); // Function ChromaSDKPlugin.*d4d7e654ba.SubtractNonZeroAllKeysName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6989bd4
	void AddNonZeroAllKeys(); // Function ChromaSDKPlugin.*d4d7e654ba.AddNonZeroAllKeys // Final|Native|Static|Public|BlueprintCallable // @ game+0x6976ae8
	void MultiplyIntensityAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyIntensityAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x6982dd0
	void SetKeyColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeyColorName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x69864a4
	void AddNonZeroTargetAllKeysAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.AddNonZeroTargetAllKeysAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697736c
	void InsertDelayName(); // Function ChromaSDKPlugin.*d4d7e654ba.InsertDelayName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6981258
	void DuplicateMirrorFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.DuplicateMirrorFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697bbd0
	void FillThresholdColorsRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.FillThresholdColorsRGB // Final|Native|Static|Public|BlueprintCallable // @ game+0x697ea10
	void MakeBlankFramesRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.MakeBlankFramesRGB // Final|Native|Static|Public|BlueprintCallable // @ game+0x69820b8
	void CopyNonZeroKeyColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroKeyColorName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697a174
	void GetKeyColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.GetKeyColorName // Final|Native|Static|Public|HasDefaults|BlueprintCallable // @ game+0x6980800
	void MultiplyIntensityRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyIntensityRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6983ab8
	void SubtractNonZeroTargetAllKeysAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.SubtractNonZeroTargetAllKeysAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x6989d54
	void FillZeroColorRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.FillZeroColorRGB // Final|Native|Static|Public|BlueprintCallable // @ game+0x697fb34
	void MultiplyIntensity(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyIntensity // Final|Native|Static|Public|BlueprintCallable // @ game+0x6982cb8
	void FillZeroColorAllFramesRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.FillZeroColorAllFramesRGB // Final|Native|Static|Public|BlueprintCallable // @ game+0x697f6b8
	void SetKeyColorAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeyColorAllFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6986344
	void CloseAnimation(); // Function ChromaSDKPlugin.*d4d7e654ba.CloseAnimation // Final|Native|Static|Public|BlueprintCallable // @ game+0x6978268
	void TrimFrameName(); // Function ChromaSDKPlugin.*d4d7e654ba.TrimFrameName // Final|Native|Static|Public|BlueprintCallable // @ game+0x698a630
	void SetChromaCustomColorAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetChromaCustomColorAllFramesName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6985bc0
	void FillColor(); // Function ChromaSDKPlugin.*d4d7e654ba.FillColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697c050
	void FillRandomColors(); // Function ChromaSDKPlugin.*d4d7e654ba.FillRandomColors // Final|Native|Static|Public|BlueprintCallable // @ game+0x697d748
	void FillNonZeroColorAllFramesRGBName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillNonZeroColorAllFramesRGBName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697d094
	void CreateColors1D(); // Function ChromaSDKPlugin.*d4d7e654ba.CreateColors1D // Final|Native|Static|Public|BlueprintCallable // @ game+0x697b33c
	void CopyNonZeroAllKeysName(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroAllKeysName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6979b18
	void UsePreloadingName(); // Function ChromaSDKPlugin.*d4d7e654ba.UsePreloadingName // Final|Native|Static|Public|BlueprintCallable // @ game+0x698ace0
	void OffsetNonZeroColorsAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.OffsetNonZeroColorsAllFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x6984afc
	void PlayAnimationName(); // Function ChromaSDKPlugin.*d4d7e654ba.PlayAnimationName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6985478
	void MakeBlankFramesRandom(); // Function ChromaSDKPlugin.*d4d7e654ba.MakeBlankFramesRandom // Final|Native|Static|Public|BlueprintCallable // @ game+0x69824f8
	void SetKeysNonZeroColorAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeysNonZeroColorAllFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6988118
	void SetKeyColorAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeyColorAllFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x69861c4
	void AddNonZeroAllKeysName(); // Function ChromaSDKPlugin.*d4d7e654ba.AddNonZeroAllKeysName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697710c
	void ClearAll(); // Function ChromaSDKPlugin.*d4d7e654ba.ClearAll // Final|Native|Static|Public|BlueprintCallable // @ game+0x6978174
	void DuplicateFirstFrame(); // Function ChromaSDKPlugin.*d4d7e654ba.DuplicateFirstFrame // Final|Native|Static|Public|BlueprintCallable // @ game+0x697b828
	void MultiplyColorLerpAllFramesName(); // Function ChromaSDKPlugin.*d4d7e654ba.MultiplyColorLerpAllFramesName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6982b3c
	void FillNonZeroColorAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.FillNonZeroColorAllFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697cd10
	void GetCurrentFrame(); // Function ChromaSDKPlugin.*d4d7e654ba.GetCurrentFrame // Final|Native|Static|Public|BlueprintCallable // @ game+0x69803f0
	void GetFrameCount(); // Function ChromaSDKPlugin.*d4d7e654ba.GetFrameCount // Final|Native|Static|Public|BlueprintCallable // @ game+0x698054c
	void LoadAnimation(); // Function ChromaSDKPlugin.*d4d7e654ba.LoadAnimation // Final|Native|Static|Public|BlueprintCallable // @ game+0x6981c64
	void FillColorAllFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.FillColorAllFrames // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x697c194
	void FillRandomColorsBlackAndWhiteName(); // Function ChromaSDKPlugin.*d4d7e654ba.FillRandomColorsBlackAndWhiteName // Final|Native|Static|Public|BlueprintCallable // @ game+0x697db78
	void StreamGetKey(); // Function ChromaSDKPlugin.*d4d7e654ba.StreamGetKey // Final|Native|Static|Public|BlueprintCallable // @ game+0x69890c4
	void *1b7385f4fe(); // Function ChromaSDKPlugin.*d4d7e654ba.*1b7385f4fe // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6977d7c
	void SubtractNonZeroAllKeysAllFramesOffset(); // Function ChromaSDKPlugin.*d4d7e654ba.SubtractNonZeroAllKeysAllFramesOffset // Final|Native|Static|Public|BlueprintCallable // @ game+0x6989904
	void SetMouseLedColor(); // Function ChromaSDKPlugin.*d4d7e654ba.SetMouseLedColor // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x698860c
	void FillThresholdColorsMinMaxAllFramesRGB(); // Function ChromaSDKPlugin.*d4d7e654ba.FillThresholdColorsMinMaxAllFramesRGB // Final|Native|Static|Public|BlueprintCallable // @ game+0x697e3e0
	void CopyNonZeroAllKeysOffset(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyNonZeroAllKeysOffset // Final|Native|Static|Public|BlueprintCallable // @ game+0x6979c98
	void UseIdleAnimations(); // Function ChromaSDKPlugin.*d4d7e654ba.UseIdleAnimations // Final|Native|Static|Public|BlueprintCallable // @ game+0x698ab68
	void StopAnimations(); // Function ChromaSDKPlugin.*d4d7e654ba.StopAnimations // Final|Native|Static|Public|HasOutParms|BlueprintCallable // @ game+0x6988b5c
	void SetIdleAnimationName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetIdleAnimationName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6985f68
	void ClearAnimationType(); // Function ChromaSDKPlugin.*d4d7e654ba.ClearAnimationType // Final|Native|Static|Public|BlueprintCallable // @ game+0x69781c4
	void SetKeyNonZeroColorName(); // Function ChromaSDKPlugin.*d4d7e654ba.SetKeyNonZeroColorName // Final|Native|Static|Public|HasOutParms|HasDefaults|BlueprintCallable // @ game+0x6986adc
	void DuplicateFrames(); // Function ChromaSDKPlugin.*d4d7e654ba.DuplicateFrames // Final|Native|Static|Public|BlueprintCallable // @ game+0x697ba10
	void SubtractNonZeroAllKeysAllFramesOffsetName(); // Function ChromaSDKPlugin.*d4d7e654ba.SubtractNonZeroAllKeysAllFramesOffsetName // Final|Native|Static|Public|BlueprintCallable // @ game+0x6989a54
	void GetKeyboardRazerKey(); // Function ChromaSDKPlugin.*d4d7e654ba.GetKeyboardRazerKey // Final|Native|Static|Public|BlueprintCallable // @ game+0x6980a7c
	void CreateRandomColors2D(); // Function ChromaSDKPlugin.*d4d7e654ba.CreateRandomColors2D // Final|Native|Static|Public|BlueprintCallable // @ game+0x697b5c4
	void StreamGetId(); // Function ChromaSDKPlugin.*d4d7e654ba.StreamGetId // Final|Native|Static|Public|BlueprintCallable // @ game+0x6988fb4
	void CopyAllKeys(); // Function ChromaSDKPlugin.*d4d7e654ba.CopyAllKeys // Final|Native|Static|Public|BlueprintCallable // @ game+0x69783a0
};

